package trms_Models;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * CourseTypes Value Object.
  * This class is value object representing database table CourseTypes
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class CourseTypes implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int courseID;
    private String courseType;
    private int percentPay;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public CourseTypes () {

    }

    public CourseTypes (int courseIDIn) {

          this.courseID = courseIDIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getCourseID() {
          return this.courseID;
    }
    public void setCourseID(int courseIDIn) {
          this.courseID = courseIDIn;
    }

    public String getCourseType() {
          return this.courseType;
    }
    public void setCourseType(String courseTypeIn) {
          this.courseType = courseTypeIn;
    }

    public int getPercentPay() {
          return this.percentPay;
    }
    public void setPercentPay(int percentPayIn) {
          this.percentPay = percentPayIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int courseIDIn,
          String courseTypeIn,
          int percentPayIn) {
          this.courseID = courseIDIn;
          this.courseType = courseTypeIn;
          this.percentPay = percentPayIn;
    }


    /** 
     * hasEqualMapping-method will compare two CourseTypes instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(CourseTypes valueObject) {

          if (valueObject.getCourseID() != this.courseID) {
                    return(false);
          }
          if (this.courseType == null) {
                    if (valueObject.getCourseType() != null)
                           return(false);
          } else if (!this.courseType.equals(valueObject.getCourseType())) {
                    return(false);
          }
          if (valueObject.getPercentPay() != this.percentPay) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass CourseTypes, mapping to table CourseTypes\n");
        out.append("Persistent attributes: \n"); 
        out.append("courseID = " + this.courseID + "\n"); 
        out.append("courseType = " + this.courseType + "\n"); 
        out.append("percentPay = " + this.percentPay + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        CourseTypes cloned = new CourseTypes();

        cloned.setCourseID(this.courseID); 
        if (this.courseType != null)
             cloned.setCourseType(new String(this.courseType)); 
        cloned.setPercentPay(this.percentPay); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}


             