package trms_Models;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Event Value Object.
  * This class is value object representing database table Event
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Event implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int eventID;
    private String eventName;
    private int eventType;
    private int eventAmount;
    private int eventDate;
    private int eventTime;
    private String eventLocation;
    private String eventDescription;
    private int eventCost;
    private int gradeFormatID;
    private int courseID;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Event () {

    }

    public Event (int eventIDIn) {

          this.eventID = eventIDIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getEventID() {
          return this.eventID;
    }
    public void setEventID(int eventIDIn) {
          this.eventID = eventIDIn;
    }

    public String getEventName() {
          return this.eventName;
    }
    public void setEventName(String eventNameIn) {
          this.eventName = eventNameIn;
    }

    public int getEventType() {
          return this.eventType;
    }
    public void setEventType(int eventTypeIn) {
          this.eventType = eventTypeIn;
    }

    public int getEventAmount() {
          return this.eventAmount;
    }
    public void setEventAmount(int eventAmountIn) {
          this.eventAmount = eventAmountIn;
    }

    public int getEventDate() {
          return this.eventDate;
    }
    public void setEventDate(int eventDateIn) {
          this.eventDate = eventDateIn;
    }

    public int getEventTime() {
          return this.eventTime;
    }
    public void setEventTime(int eventTimeIn) {
          this.eventTime = eventTimeIn;
    }

    public String getEventLocation() {
          return this.eventLocation;
    }
    public void setEventLocation(String eventLocationIn) {
          this.eventLocation = eventLocationIn;
    }

    public String getEventDescription() {
          return this.eventDescription;
    }
    public void setEventDescription(String eventDescriptionIn) {
          this.eventDescription = eventDescriptionIn;
    }

    public int getEventCost() {
          return this.eventCost;
    }
    public void setEventCost(int eventCostIn) {
          this.eventCost = eventCostIn;
    }

    public int getGradeFormatID() {
          return this.gradeFormatID;
    }
    public void setGradeFormatID(int gradeFormatIDIn) {
          this.gradeFormatID = gradeFormatIDIn;
    }

    public int getCourseID() {
          return this.courseID;
    }
    public void setCourseID(int courseIDIn) {
          this.courseID = courseIDIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int eventIDIn,
          String eventNameIn,
          int eventTypeIn,
          int eventAmountIn,
          int eventDateIn,
          int eventTimeIn,
          String eventLocationIn,
          String eventDescriptionIn,
          int eventCostIn,
          int gradeFormatIDIn,
          int courseIDIn) {
          this.eventID = eventIDIn;
          this.eventName = eventNameIn;
          this.eventType = eventTypeIn;
          this.eventAmount = eventAmountIn;
          this.eventDate = eventDateIn;
          this.eventTime = eventTimeIn;
          this.eventLocation = eventLocationIn;
          this.eventDescription = eventDescriptionIn;
          this.eventCost = eventCostIn;
          this.gradeFormatID = gradeFormatIDIn;
          this.courseID = courseIDIn;
    }


    /** 
     * hasEqualMapping-method will compare two Event instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Event valueObject) {

          if (valueObject.getEventID() != this.eventID) {
                    return(false);
          }
          if (this.eventName == null) {
                    if (valueObject.getEventName() != null)
                           return(false);
          } else if (!this.eventName.equals(valueObject.getEventName())) {
                    return(false);
          }
          if (valueObject.getEventType() != this.eventType) {
                    return(false);
          }
          if (valueObject.getEventAmount() != this.eventAmount) {
                    return(false);
          }
          if (valueObject.getEventDate() != this.eventDate) {
                    return(false);
          }
          if (valueObject.getEventTime() != this.eventTime) {
                    return(false);
          }
          if (this.eventLocation == null) {
                    if (valueObject.getEventLocation() != null)
                           return(false);
          } else if (!this.eventLocation.equals(valueObject.getEventLocation())) {
                    return(false);
          }
          if (this.eventDescription == null) {
                    if (valueObject.getEventDescription() != null)
                           return(false);
          } else if (!this.eventDescription.equals(valueObject.getEventDescription())) {
                    return(false);
          }
          if (valueObject.getEventCost() != this.eventCost) {
                    return(false);
          }
          if (valueObject.getGradeFormatID() != this.gradeFormatID) {
                    return(false);
          }
          if (valueObject.getCourseID() != this.courseID) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Event, mapping to table Event\n");
        out.append("Persistent attributes: \n"); 
        out.append("eventID = " + this.eventID + "\n"); 
        out.append("eventName = " + this.eventName + "\n"); 
        out.append("eventType = " + this.eventType + "\n"); 
        out.append("eventAmount = " + this.eventAmount + "\n"); 
        out.append("eventDate = " + this.eventDate + "\n"); 
        out.append("eventTime = " + this.eventTime + "\n"); 
        out.append("eventLocation = " + this.eventLocation + "\n"); 
        out.append("eventDescription = " + this.eventDescription + "\n"); 
        out.append("eventCost = " + this.eventCost + "\n"); 
        out.append("gradeFormatID = " + this.gradeFormatID + "\n"); 
        out.append("courseID = " + this.courseID + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Event cloned = new Event();

        cloned.setEventID(this.eventID); 
        if (this.eventName != null)
             cloned.setEventName(new String(this.eventName)); 
        cloned.setEventType(this.eventType); 
        cloned.setEventAmount(this.eventAmount); 
        cloned.setEventDate(this.eventDate); 
        cloned.setEventTime(this.eventTime); 
        if (this.eventLocation != null)
             cloned.setEventLocation(new String(this.eventLocation)); 
        if (this.eventDescription != null)
             cloned.setEventDescription(new String(this.eventDescription)); 
        cloned.setEventCost(this.eventCost); 
        cloned.setGradeFormatID(this.gradeFormatID); 
        cloned.setCourseID(this.courseID); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}


             